[
    {
        "id": 1,
        "name": "Nagendra Kumar Subudhi",
        "amount": 100000,
        "year": "2021-22",
        "batch": "2021-22",
        "department": "Engineering",
        "currentRole": "Lead Specialist",
        "organization": "ZTE Telecom India Pvt. Ltd.",
        "location": "Hyderabad, India",
        "photo": "donateImages/nagendra-subudhi.jpeg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Alumni Endowment Fund",
        "verified": true
    },
    {
        "id": 2,
        "name": "GIET Alumni Association",
        "amount": 1150000,
        "year": "2018-19",
        "batch": "2018-19",
        "department": "Alumni Relations",
        "currentRole": "Alumni Benefactor",
        "organization": "GIET University, Gunupur",
        "location": "Gunupur, Odisha, India",
        "photo": "donateImages/alumni-rep-1.jpeg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Alumni Student Contributions",
        "verified": true
    },
    {
        "id": 3,
        "name": "GIET Alumni Association",
        "amount": 962200,
        "year": "2019-20",
        "batch": "2019-20",
        "department": "Campus Infrastructure",
        "currentRole": "Alumni Benefactor",
        "organization": "GIET University, Gunupur",
        "location": "Gunupur, Odisha, India",
        "photo": "donateImages/alumni-rep-2.jpeg",
        "linkedin": "",
        "donationType": "Equipment",
        "donationItem": "CCTV Cameras & Surveillance",
        "verified": true
    },
    {
        "id": 4,
        "name": "GIET Alumni Association",
        "amount": 138200,
        "year": "2020-21",
        "batch": "2020-21",
        "department": "Campus Amenities",
        "currentRole": "Alumni Benefactor",
        "organization": "GIET University, Gunupur",
        "location": "Gunupur, Odisha, India",
        "photo": "donateImages/alumni-rep-3.jpeg",
        "linkedin": "",
        "donationType": "Equipment",
        "donationItem": "Water Purifier & Cooler",
        "verified": true
    },
    {
        "id": 5,
        "name": "GIET Alumni Association",
        "amount": 288266,
        "year": "2022-23",
        "batch": "2022-23",
        "department": "Smart Classroom Tech",
        "currentRole": "Alumni Benefactor",
        "organization": "GIET University, Gunupur",
        "location": "Gunupur, Odisha, India",
        "photo": "donateImages/alumni-rep-4.jpeg",
        "linkedin": "",
        "donationType": "Equipment",
        "donationItem": "Digital Classroom Projector",
        "verified": true
    },
    {
        "id": 6,
        "name": "Rajesh Pattnaik",
        "amount": 25000,
        "year": "2015-16",
        "batch": "2015-16",
        "department": "Computer Science & Engineering",
        "currentRole": "Senior Systems Engineer",
        "organization": "Tata Consultancy Services",
        "location": "Bhubaneswar, India",
        "photo": "donateImages/donor-6.jpeg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Student Scholarship Fund",
        "verified": true
    },
    {
        "id": 7,
        "name": "Soumya Ranjan Tripathy",
        "amount": 50000,
        "year": "2013-14",
        "batch": "2013-14",
        "department": "Information Technology",
        "currentRole": "Cloud Solutions Architect",
        "organization": "Infosys Ltd.",
        "location": "Bengaluru, India",
        "photo": "donateImages/donor-7.jpeg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Laboratory Innovation Grant",
        "verified": true
    },
    {
        "id": 8,
        "name": "Amit Kumar Panda",
        "amount": 15000,
        "year": "2016-17",
        "batch": "2016-17",
        "department": "Electronics & Communication",
        "currentRole": "Lead Embedded Engineer",
        "organization": "Wipro Technologies",
        "location": "Hyderabad, India",
        "photo": "donateImages/donor-8.jpeg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Campus Library Resource Fund",
        "verified": true
    },
    {
        "id": 9,
        "name": "Subham Mohanty",
        "amount": 35000,
        "year": "2011-12",
        "batch": "2011-12",
        "department": "Mechanical Engineering",
        "currentRole": "Project Manager",
        "organization": "Cognizant Technology Solutions",
        "location": "Chennai, India",
        "photo": "donor-9.jpg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Merit & Innovation Scholarship",
        "verified": true
    },
    {
        "id": 10,
        "name": "Deepak Rath",
        "amount": 75000,
        "year": "2009-10",
        "batch": "2009-10",
        "department": "Electrical & Electronics",
        "currentRole": "Principal Consultant",
        "organization": "Accenture India",
        "location": "Pune, India",
        "photo": "donor-10.jpg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Robotics & AI Research Grant",
        "verified": true
    },
    {
        "id": 11,
        "name": "Ananya Senapati",
        "amount": 18000,
        "year": "2017-18",
        "batch": "2017-18",
        "department": "Civil Engineering",
        "currentRole": "Infrastructure Specialist",
        "organization": "Tech Mahindra",
        "location": "Bhubaneswar, India",
        "photo": "donor-11.jpg",
        "linkedin": "",
        "donationType": "Alumni Contribution",
        "donationItem": "Student Welfare & Medical Aid",
        "verified": true
    }
]
